#!/usr/bin/env python3

import argparse
from mkSpellbook.core import MkSpellbook
if __name__ == "__main__":
	parser = argparse.ArgumentParser()
	parser.add_argument("--spellbook", "-s", default="My Spellbook")
	parser.add_argument("--database", "-d", default="~/.mkspellbook/spells.db")
	args = parser.parse_args()

	mkspellbook = MkSpellbook(args)
	mkspellbook.caller(mkspellbook.start)
